export const TICKET_LOADING = "APP/TICKET_LOADING";
export const TICKET_SUCCESS = "APP/TICKET_SUCCESS";
export const TICKET_FAIL = "APP/TICKET_FAIL";
export const INCREASE_TICKETS_LIMIT = "APP/INCREASE_TICKETS_LIMIT";
export const CHANGE_CHECKBOX = "APP/CHANGE_CHECKBOX";
export const CHANGE_TAB = "APP/CHANGE_TAB";
